-- ==============================================================
-- ORBITAL ARCHIVE - Seed Data
-- ==============================================================

USE `orbital_archive`;

-- Disable foreign key checks for clean truncation / seeding
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `sources`;
TRUNCATE TABLE `timeline_events`;
TRUNCATE TABLE `images`;
TRUNCATE TABLE `equipment`;
TRUNCATE TABLE `missions`;
TRUNCATE TABLE `destinations`;
TRUNCATE TABLE `agencies`;
TRUNCATE TABLE `users`;
SET FOREIGN_KEY_CHECKS = 1;

-- 1. USERS
INSERT INTO `users` (`id`, `username`, `email`, `password_hash`, `role`) VALUES
(1, 'admin', 'admin@orbitalarchive.org', '$2y$10$.CZbwNPf7UNL/cn73pUf1.njtCvLtP/oPVpYYVtKnbifJjLlijcgG', 'admin');

-- 2. AGENCIES
INSERT INTO `agencies` (`id`, `name`, `short_name`, `country`, `type`, `description`, `logo_url`, `website_url`) VALUES
(1, 'National Aeronautics and Space Administration', 'NASA', 'United States', 'National', 'Responsible for civilian space program, aeronautics research, and space exploration.', 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=100&auto=format&fit=crop', 'https://www.nasa.gov'),
(2, 'Indian Space Research Organisation', 'ISRO', 'India', 'National', 'Primary space agency of India, known for cost-effective deep space exploration including Chandrayaan and Mars Orbiter missions.', 'https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?w=100&auto=format&fit=crop', 'https://www.isro.gov.in'),
(3, 'European Space Agency', 'ESA', 'Europe (22 Nations)', 'International', 'Intergovernmental organization dedicated to the exploration of space across Europe.', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=100&auto=format&fit=crop', 'https://www.esa.int'),
(4, 'Japan Aerospace Exploration Agency', 'JAXA', 'Japan', 'National', 'National aerospace agency conducting satellite launches, lunar exploration, and asteroid sample return missions.', 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=100&auto=format&fit=crop', 'https://global.jaxa.jp'),
(5, 'China National Space Administration', 'CNSA', 'China', 'National', 'National space agency of China, leading the Chang''e lunar program, Tianwen Mars exploration, and Tiangong station.', 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=100&auto=format&fit=crop', 'http://www.cnsa.gov.cn'),
(6, 'State Space Corporation Roscosmos / Soviet Program', 'Roscosmos', 'Russia / USSR', 'National', 'Historic pioneer of space exploration, including Sputnik, Vostok, Luna, Venera, and Mir programs.', 'https://images.unsplash.com/photo-1517976487502-d7da6e3820a1?w=100&auto=format&fit=crop', 'https://www.roscosmos.ru'),
(7, 'Space Exploration Technologies Corp.', 'SpaceX', 'United States', 'Commercial', 'Pioneering private aerospace manufacturer and space transportation services company with reusable rockets and Starship.', 'https://images.unsplash.com/photo-1517976487502-d7da6e3820a1?w=100&auto=format&fit=crop', 'https://www.spacex.com'),
(8, 'Rocket Lab', 'Rocket Lab', 'United States / New Zealand', 'Commercial', 'Leading aerospace manufacturer and small satellite launch service provider operating the Electron rocket.', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=100&auto=format&fit=crop', 'https://www.rocketlabusa.com'),
(9, 'Intuitive Machines', 'Intuitive Machines', 'United States', 'Commercial', 'Commercial space exploration company delivering payloads to the Moon under NASA''s CLPS initiative.', 'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=100&auto=format&fit=crop', 'https://www.intuitivemachines.com');

-- 3. DESTINATIONS
INSERT INTO `destinations` (`id`, `name`, `type`, `description`, `distance_from_earth`, `mission_count`, `image_url`) VALUES
(1, 'Earth Orbit', 'Low Earth & Geostationary Orbit', 'The orbital envelope encompassing low, medium, and geostationary orbits where humanity maintains active space stations and constellations.', '400 km – 35,786 km', 9120, 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=600&auto=format&fit=crop'),
(2, 'Moon', 'Lunar Surface & Orbit', 'Earth''s only natural satellite, the farthest destination reached by human feet and site of hundreds of historic and modern robotic probes.', '384,400 km', 142, 'https://images.unsplash.com/photo-1532693322450-2cb5c511067d?w=600&auto=format&fit=crop'),
(3, 'Mars', 'Martian Surface & Atmosphere', 'The Red Planet, host to robotic rovers, landers, and orbiters seeking past water and evidence of ancient microbial life.', '54.6M – 401M km', 56, 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=600&auto=format&fit=crop'),
(4, 'Venus', 'Cytherean Atmosphere & Surface', 'Earth''s scorching twin with an extreme runaway greenhouse atmosphere and crushing surface pressures.', '38M – 261M km', 45, 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=600&auto=format&fit=crop'),
(5, 'Asteroids & Comets', 'Small Solar System Bodies', 'Pristine remnants of the early solar system investigated by sample return and impactor missions.', '100M – 700M km', 24, 'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=600&auto=format&fit=crop'),
(6, 'Outer Solar System', 'Gas Giants & Kuiper Belt', 'The outer frontiers including Jupiter, Saturn, Uranus, Neptune, and the dwarf planet Pluto.', '600M – 5.9B km', 18, 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop'),
(7, 'Deep Space / Interstellar', 'Heliopause & Interstellar Space', 'The boundless expanse beyond the Sun''s heliosphere traversed by humanity''s farthest interstellar travelers.', '24+ Billion km', 21, 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=600&auto=format&fit=crop');

-- 4. MISSIONS
INSERT INTO `missions` (`id`, `name`, `official_name`, `agency_id`, `launch_date`, `launch_vehicle`, `launch_location`, `launch_lat`, `launch_lng`, `arrival_date`, `destination_id`, `objective`, `status`, `trajectory_type`, `mission_end_date`, `end_reason`, `description`, `legacy`) VALUES
(1, 'Apollo 11', 'Apollo 11 Lunar Landing', 1, '1969-07-16', 'Saturn V', 'Kennedy Space Center LC-39A, FL, USA', 28.572872, -80.648981, '1969-07-20', 2, 'Perform a crewed lunar landing and return safely to Earth.', 'Completed', 'Crewed', '1969-07-24', 'Successful splashdown in Pacific Ocean', 'First human landing on the lunar surface. Neil Armstrong and Buzz Aldrin spent 21.5 hours on the surface.', 'Achieved President Kennedy''s national goal and proved humans could travel to another celestial body.'),
(2, 'Apollo 15', 'Apollo 15 Lunar Roving Mission', 1, '1971-07-26', 'Saturn V', 'Kennedy Space Center LC-39A, FL, USA', 28.572872, -80.648981, '1971-07-30', 2, 'Longer stay on the Moon with first deployment of the Lunar Roving Vehicle for geological exploration of Hadley Rille.', 'Completed', 'Crewed', '1971-08-07', 'Successful splashdown', 'Fourth crewed lunar landing and the first of the Apollo J-missions designed for extended scientific exploration.', 'Introduced mobile surface exploration on the Moon, driving 27.8 km across Hadley Rille and Apennine mountains.'),
(3, 'Voyager 1', 'Voyager Interstellar Mission 1', 1, '1977-09-05', 'Titan IIIE / Centaur', 'Cape Canaveral SLC-41, FL, USA', 28.583333, -80.583333, '1979-03-05', 7, 'Explore Jupiter and Saturn systems, then advance into the interstellar medium.', 'Active', 'Robotic probe', NULL, NULL, 'Currently humanity''s farthest active human-made object, operating in interstellar space over 24 billion km from Earth.', 'Carries the Golden Record and discovered volcanic activity on Io, complex rings at Saturn, and crossed the heliopause in 2012.'),
(4, 'Voyager 2', 'Voyager Interstellar Mission 2', 1, '1977-08-20', 'Titan IIIE / Centaur', 'Cape Canaveral SLC-41, FL, USA', 28.583333, -80.583333, '1979-07-09', 7, 'Perform a grand tour of Jupiter, Saturn, Uranus, and Neptune, entering interstellar space.', 'Active', 'Robotic probe', NULL, NULL, 'The only spacecraft to visit all four outer gas giant planets of our solar system.', 'Provided humanity''s first close-up photographs and measurements of Uranus and Neptune.'),
(5, 'Mars Pathfinder', 'Mars Pathfinder / Sojourner', 1, '1996-12-04', 'Delta II 7925', 'Cape Canaveral SLC-17B, FL, USA', 28.528333, -80.565833, '1997-07-04', 3, 'Demonstrate cost-effective landing with airbags and operate the first mobile wheeled rover on Mars.', 'Completed', 'Robotic probe', '1997-09-27', 'Battery depletion and communications loss', 'Delivered the micro-rover Sojourner to Ares Vallis, testing Martian rocks and atmospheric conditions.', 'Proved the feasibility of planetary rovers, pioneering the robotic roving architecture used for decades.'),
(6, 'Mars Exploration Rover A: Spirit', 'MER-A (Spirit)', 1, '2003-06-10', 'Delta II 7925', 'Cape Canaveral SLC-17A, FL, USA', 28.528333, -80.565833, '2004-01-04', 3, 'Search for and characterize a wide range of rocks and soils that hold clues to past water activity in Gusev Crater.', 'Completed', 'Robotic probe', '2010-03-22', 'Trapped in soft soil; communications ceased during winter', 'Explored Gusev Crater and Columbia Hills for over 6 years on a planned 90-day mission.', 'Uncovered evidence of hydrothermal systems and ancient volcanic explosive activity on Mars.'),
(7, 'Mars Exploration Rover B: Opportunity', 'MER-B (Opportunity)', 1, '2003-07-07', 'Delta II 7925H', 'Cape Canaveral SLC-17B, FL, USA', 28.528333, -80.565833, '2004-01-25', 3, 'Search for clues about past water and habitability across Meridiani Planum.', 'Completed', 'Robotic probe', '2018-06-10', 'Catastrophic planet-encircling dust storm blocked solar arrays', 'Traveled an unprecedented 45.16 kilometers across the surface of Mars, operating for nearly 15 years.', 'Discovered hematite blueberries and indisputable mineral evidence of past liquid water on Mars.'),
(8, 'Mars Science Laboratory: Curiosity', 'Curiosity Rover', 1, '2011-11-26', 'Atlas V 541', 'Cape Canaveral SLC-41, FL, USA', 28.583333, -80.583333, '2012-08-06', 3, 'Determine whether Mars could have ever supported microbial life inside Gale Crater.', 'Active', 'Robotic probe', NULL, NULL, 'Nuclear-powered science laboratory climbing Mount Sharp inside Gale Crater.', 'Confirmed Gale Crater was once a habitable lake environment containing organic carbon molecules.'),
(9, 'Mars 2020: Perseverance', 'Perseverance Rover & Ingenuity', 1, '2020-07-30', 'Atlas V 541', 'Cape Canaveral SLC-41, FL, USA', 28.583333, -80.583333, '2021-02-18', 3, 'Seek signs of ancient life, collect cache of Martian rock cores for Earth return, test MOXIE oxygen generation.', 'Active', 'Robotic probe', NULL, NULL, 'Exploring Jezero Crater delta and riverbed deposits while testing technologies for future human exploration.', 'Discovered organic biosignature candidates and deployed the first powered aircraft on another planet.'),
(10, 'Mars Helicopter: Ingenuity', 'Ingenuity Rotorcraft', 1, '2020-07-30', 'Atlas V 541', 'Cape Canaveral SLC-41, FL, USA', 28.583333, -80.583333, '2021-02-18', 3, 'Demonstrate powered, controlled aerodynamic flight in the thin atmosphere of Mars.', 'Completed', 'Robotic probe', '2024-01-25', 'Rotor blade damaged during final landing', 'Completed 72 historic flights across 17 km of Martian terrain, far surpassing its 5-flight tech demo goal.', 'Proved aerial exploration is possible in other planetary atmospheres.'),
(11, 'Phoenix Mars Lander', 'Phoenix Scout Mission', 1, '2007-08-04', 'Delta II 7925', 'Cape Canaveral SLC-17A, FL, USA', 28.528333, -80.565833, '2008-05-25', 3, 'Study the history of water in the Martian arctic plains and evaluate habitability of permafrost.', 'Completed', 'Robotic probe', '2008-11-02', 'Loss of solar power in Martian arctic winter', 'Touched down at Vastitas Borealis, dug into soil, and scraped direct subsurface water ice.', 'Directly confirmed water ice just centimeters beneath Martian soil.'),
(12, 'InSight Lander', 'Interior Exploration using Seismic Investigations', 1, '2018-05-05', 'Atlas V 401', 'Vandenberg Space Force Base SLC-3E, CA, USA', 34.742000, -120.572400, '2018-11-26', 3, 'Study the deep interior structure of Mars, measuring marsquakes, core size, and crustal thickness.', 'Completed', 'Robotic probe', '2022-12-15', 'Dust accumulation on solar panels depleted battery', 'Recorded over 1,300 marsquakes and mapped the core, mantle, and crust of Mars.', 'Revealed that Mars has a liquid metallic core and is seismically active.'),
(13, 'Chandrayaan-1', 'Chandrayaan-1 Lunar Mission', 2, '2008-10-22', 'PSLV-C11', 'Satish Dhawan Space Centre SLP, Sriharikota, India', 13.719900, 80.230500, '2008-11-08', 2, 'Orbital survey of Moon’s topography, chemical composition, and search for water.', 'Completed', 'Robotic probe', '2009-08-29', 'Telemetry loss after orbital mission success', 'India''s first lunar probe, operated the Moon Impact Probe that touched down at Shackleton Crater.', 'Confirmed widespread presence of hydroxyl and water molecules on the lunar surface with NASA''s M3 instrument.'),
(14, 'Chandrayaan-3', 'Chandrayaan-3 Lunar Landing Mission', 2, '2023-07-14', 'LVM3 M4', 'Satish Dhawan Space Centre SLP, Sriharikota, India', 13.719900, 80.230500, '2023-08-23', 2, 'Demonstrate safe soft-landing near the lunar south polar region and roving capabilities.', 'Completed', 'Robotic probe', '2023-09-04', 'Completed full primary lunar day mission; entered planned sleep', 'First spacecraft in human history to successfully land near the Moon’s southern polar region.', 'Established India as the 4th country to achieve a soft lunar landing and measured in-situ plasma and temperature gradients.'),
(15, 'Hayabusa2', 'Hayabusa2 Asteroid Sample Return', 4, '2014-12-03', 'H-IIA 202', 'Tanegashima Space Center Yoshinobu Launch Complex, Japan', 30.400000, 130.970000, '2018-06-27', 5, 'Rendezvous with near-Earth asteroid Ryugu, deploy rovers, fire impactor, and return samples to Earth.', 'Active', 'Robotic probe', NULL, NULL, 'Successfully returned pristine Ryugu asteroid samples to Earth in 2020; currently cruising to target 1998 KY26.', 'Delivered organic compounds, amino acids, and water-bearing minerals from a primitive asteroid.'),
(16, 'Rosetta', 'Rosetta Comet Rendezvous', 3, '2004-03-02', 'Ariane 5 G+', 'Guiana Space Centre ELA-3, Kourou, French Guiana', 5.239000, -52.768000, '2014-08-06', 5, 'Rendezvous with Comet 67P/Churyumov–Gerasimenko, accompany its perihelion passage, and deploy lander.', 'Completed', 'Robotic probe', '2016-09-30', 'Controlled impact into comet surface at mission conclusion', 'First spacecraft to orbit a comet nucleus and escort it as it approached the Sun.', 'Analyzed comet dust, gases, organic molecules, and isotopic water composition.'),
(17, 'Philae', 'Philae Robotic Comet Lander', 3, '2004-03-02', 'Ariane 5 G+', 'Guiana Space Centre ELA-3, Kourou, French Guiana', 5.239000, -52.768000, '2014-11-12', 5, 'Perform the first soft touchdown on a comet nucleus and conduct surface science.', 'Completed', 'Robotic probe', '2015-07-09', 'Landed in shaded crevice; last signal received July 2015', 'Separated from Rosetta and performed humanity''s first comet surface landing on 67P.', 'Detected complex organic carbon molecules in comet nucleus material.'),
(18, 'New Horizons', 'New Horizons Pluto & Kuiper Belt', 1, '2006-01-19', 'Atlas V 551', 'Cape Canaveral SLC-41, FL, USA', 28.583333, -80.583333, '2015-07-14', 6, 'First reconnaissance of the Pluto system and exploration of Kuiper Belt object Arrokoth.', 'Active', 'Robotic probe', NULL, NULL, 'Fastest spacecraft at launch, flying past Pluto in July 2015 and Arrokoth on New Year''s Day 2019.', 'Revealed nitrogen ice glaciers, mountain ranges, and dynamic atmospheric hazes on Pluto.'),
(19, 'Cassini-Huygens', 'Cassini Saturn Orbiter', 1, '1997-10-15', 'Titan IVB / Centaur', 'Cape Canaveral SLC-40, FL, USA', 28.561944, -80.577222, '2004-07-01', 6, 'Study Saturn, its spectacular ring system, and its moons in unprecedented detail for 13 years.', 'Completed', 'Robotic probe', '2017-09-15', 'Grand Finale intentional atmospheric plunge into Saturn', 'Discovered active cryovolcanic plumes of water ice erupting from Enceladus and methane seas on Titan.', 'Fundamentally transformed our understanding of ocean worlds and extraterrestrial habitability.'),
(20, 'Hubble Space Telescope', 'HST Orbital Observatory', 1, '1990-04-24', 'Space Shuttle Discovery STS-31', 'Kennedy Space Center LC-39B, FL, USA', 28.627222, -80.620833, '1990-04-25', 1, 'Observe distant stars, galaxies, and nebulae without atmospheric distortion across UV, visible, and NIR.', 'Active', 'Satellite', NULL, NULL, 'One of NASA''s Great Observatories, serviced 5 times by Shuttle astronauts in Low Earth Orbit.', 'Measured rate of cosmic expansion, confirmed supermassive black holes, and peered into the Deep Field.'),
(21, 'James Webb Space Telescope', 'JWST Flagship Observatory', 1, '2021-12-25', 'Ariane 5 ECA', 'Guiana Space Centre ELA-3, Kourou, French Guiana', 5.239000, -52.768000, '2022-01-24', 7, 'Observe the first galaxies formed after the Big Bang, stellar nurseries, and exoplanet atmospheres at Sun-Earth L2.', 'Active', 'Satellite', NULL, NULL, 'Largest optical telescope in space with a 6.5-meter gold-coated beryllium primary mirror.', 'Detects first-generation galaxies and chemical signatures in atmospheres of alien exoplanets.'),
(22, 'Sputnik 1', 'PS-1 (Prosteyshiy Sputnik 1)', 6, '1957-10-04', 'Sputnik 8K71PS', 'Baikonur Cosmodrome Site 1/5, Kazakhstan', 45.964585, 63.305244, '1957-10-04', 1, 'Place the first artificial satellite into Earth orbit and broadcast radio beeps.', 'Completed', 'Satellite', '1958-01-04', 'Orbital decay and atmospheric re-entry after 1,440 orbits', 'Inaugurated the Space Age and ignited humanity''s push into space technology.', 'The radio transmitter emitted pulsed beeps that could be heard around the world.'),
(23, 'Aditya-L1', 'Aditya-L1 Solar Observatory', 2, '2023-09-02', 'PSLV-C57', 'Satish Dhawan Space Centre FLP, Sriharikota, India', 13.719900, 80.230500, '2024-01-06', 7, 'Study the solar atmosphere, chromosphere, photosphere, coronal heating, and space weather from Sun-Earth L1.', 'Active', 'Robotic probe', NULL, NULL, 'India''s first dedicated solar observatory mission stationed at Lagrange point L1, 1.5 million km from Earth.', 'Provides continuous uninterrupted observation of the Sun, solar flares, and coronal mass ejections.'),
(24, 'AstroSat', 'AstroSat Multi-wavelength Observatory', 2, '2015-09-28', 'PSLV-C30', 'Satish Dhawan Space Centre FLP, Sriharikota, India', 13.719900, 80.230500, '2015-09-28', 1, 'Observe astrophysical objects across optical, ultraviolet, and X-ray spectral bands simultaneously.', 'Active', 'Satellite', NULL, NULL, 'India''s first dedicated multi-wavelength space astronomy observatory.', 'Discovered rare high-energy cosmic sources, binary stars, and extreme UV emissions from distant galaxies.'),
(25, 'Gaia', 'Gaia Astrometry Mission', 3, '2013-12-19', 'Soyuz-STB / Fregat-MT', 'Guiana Space Centre ELS, Kourou, French Guiana', 5.239000, -52.768000, '2014-01-08', 7, 'Create the most precise 3D space catalog ever made of more than a billion stars in our Milky Way galaxy.', 'Active', 'Satellite', NULL, NULL, 'Stationed at Sun-Earth L2, mapping stellar positions, motions, distances, and brightness.', 'Revolutionized galactic archaeology and kinematics, cataloging over 1.8 billion celestial objects.'),
(26, 'Tianwen-1: Zhurong', 'Zhurong Mars Rover', 5, '2020-07-23', 'Long March 5 Y4', 'Wenchang Spacecraft Launch Site, Hainan, China', 19.614400, 110.951100, '2021-05-15', 3, 'Study Martian topography, soil characteristics, ice distribution, and magnetic field in Utopia Planitia.', 'Completed', 'Robotic probe', '2022-05-20', 'Entered planned hibernation for winter; dust buildup prevented reboot', 'First Chinese Mars rover, making China the second nation to operate a rover on the Martian surface.', 'Traveled nearly 2 km across Utopia Planitia finding evidence of ancient water floods and hydrated minerals.'),
(27, 'SLIM', 'Smart Lander for Investigating Moon', 4, '2023-09-07', 'H-IIA 202', 'Tanegashima Space Center, Japan', 30.400000, 130.970000, '2024-01-19', 2, 'Demonstrate high-precision pinpoint lunar landing within 100 meters of target.', 'Completed', 'Robotic probe', '2024-04-29', 'Completed multiple lunar nights beyond primary objectives', 'Successfully landed within 55 meters of its target rim at Shioli Crater, deploying LEV-1 and LEV-2 rovers.', 'Demonstrated pinpoint landing technology for future lunar and planetary scientific expeditions.'),
(28, 'Surveyor 1', 'Surveyor 1 Lunar Soft Lander', 1, '1966-05-30', 'Atlas-Centaur', 'Cape Canaveral SLC-36A, FL, USA', 28.471944, -80.575278, '1966-06-02', 2, 'Demonstrate soft landing technology and gather first close-up lunar surface television images.', 'Completed', 'Robotic probe', '1967-01-07', 'Battery power depleted after transmitting 11,237 images', 'First American spacecraft to achieve a soft touchdown on the Moon (Oceanus Procellarum).', 'Confirmed the lunar regolith could physically support the weight of the Apollo Lunar Module.'),
(29, 'Surveyor 3', 'Surveyor 3 Lunar Lander', 1, '1967-04-17', 'Atlas-Centaur', 'Cape Canaveral SLC-36B, FL, USA', 28.471944, -80.575278, '1967-04-20', 2, 'Soft land in Oceanus Procellarum and dig trench in lunar soil with robotic scoop.', 'Completed', 'Robotic probe', '1967-05-04', 'Lunar night freeze; later visited by Apollo 12 astronauts in 1969', 'Landed in a crater; Apollo 12 astronauts later walked to it, inspected it, and brought parts back to Earth.', 'Only robotic probe visited and sampled on another celestial body by human astronauts.'),
(30, 'International Space Station', 'ISS (Zarya Assembly)', 1, '1998-11-20', 'Proton-K / Space Shuttle', 'Baikonur Cosmodrome Site 81/23, Kazakhstan', 45.964585, 63.305244, '1998-11-20', 1, 'Serve as a permanently crewed microgravity laboratory for international scientific collaboration.', 'Active', 'Crewed', NULL, NULL, 'Continuously inhabited by international crews since November 2000, orbiting at 400 km altitude.', 'Largest modular structure ever built in space, conducting thousands of medical and material experiments.');

-- 5. EQUIPMENT
INSERT INTO `equipment` (`id`, `mission_id`, `name`, `official_name`, `type`, `purpose`, `technology`, `instruments`, `communication`, `operational_period`, `current_status`, `current_location`, `is_relic`, `relic_category`, `description`, `discoveries`, `legacy`) VALUES
(1, 1, 'Lunar Module Eagle', 'Apollo 11 LM-5 Descent Stage', 'Lander', 'Descent to lunar surface and touchdown platform.', 'Hypergolic rocket descent engine, aluminum honeycomb landing gear.', 'Landing radar, seismic equipment, solar wind composition foil.', 'S-band steerable antenna and VHF transceiver.', '1969-07-20 to 1969-07-21', 'Abandoned', 'Mare Tranquillitatis (0.67408° N, 23.47297° E)', 1, 'Lunar Relic', 'The descent stage of Apollo 11 Lunar Module Eagle that carried Neil Armstrong and Buzz Aldrin to the surface.', 'Enabled first human footsteps on another world.', 'A permanent monument marking the inaugural landing of humanity on another world.'),
(2, 2, 'Apollo 15 Lunar Roving Vehicle', 'LRV-1 (Hadley-Apennine)', 'Rover', 'Provide surface mobility allowing astronauts to explore distant geological features.', 'Four electric drive wheel motors, chevron wire mesh tires, zinc-silver batteries.', 'High-gain dish antenna, color TV camera, 16mm movie camera, magnetometer.', 'Direct Lunar Communications Relay Unit (LCRU) to Earth.', '1971-07-31 to 1971-08-02', 'Decommissioned', 'Hadley-Apennine (26.1322° N, 3.6339° E)', 1, 'Lunar Relic', 'The very first wheeled vehicle driven on the Moon. Traveled 27.8 km across mountains and rilles.', 'Collected the historic Genesis Rock (anorthosite dated to 4.5 billion years old).', 'The pioneer of off-world ground vehicles, remaining parked at Hadley Rille to this day.'),
(3, 3, 'Voyager 1 Spacecraft', 'Voyager 1 Interstellar Probe', 'Flyby Probe', 'Reconnaissance of Jupiter and Saturn, now studying interstellar plasma.', 'Radioisotope Thermoelectric Generators (3x RTG), hydrazine thrusters.', 'Magnetometer, Cosmic Ray Subsystem, Low Energy Charged Particle instrument.', '3.7-meter high-gain parabolic antenna communicating via Deep Space Network.', '1977-09-05 to Present', 'Operational', 'Interstellar Space (163 AU from Earth)', 1, 'Deep Space Relic', 'Humanity''s most distant spacecraft, carrying the Golden Record as a cosmic message to civilizations beyond.', 'First spacecraft to cross the heliopause into the interstellar medium (August 2012).', 'An eternal messenger of humankind traveling through the stars indefinitely.'),
(4, 4, 'Voyager 2 Spacecraft', 'Voyager 2 Outer Planet Explorer', 'Flyby Probe', 'Reconnaissance of all four outer planets and entry into interstellar space.', '3x RTGs, attitude thrusters, scan platform.', 'Planetary Radio Astronomy, Magnetometer, Cosmic Ray System.', '3.7-meter dish antenna communicating via DSN Canberra station.', '1977-08-20 to Present', 'Operational', 'Interstellar Space (136 AU from Earth)', 1, 'Deep Space Relic', 'The only human spacecraft to explore Uranus and Neptune.', 'Discovered 16 new moons and multiple ring systems across outer planets.', 'Entered interstellar space in November 2018, continuing to transmit cosmic ray data.'),
(5, 5, 'Sojourner Rover', 'Microrover Sojourner (Pathfinder)', 'Rover', 'First mobile robotic explorer on Mars.', '6-wheel rocker-bogie mobility, solar array, lithium battery backup.', 'Alpha Proton X-ray Spectrometer (APXS), forward stereo cameras.', 'UHF radio link to Pathfinder lander base station.', '1997-07-04 to 1997-09-27', 'Abandoned', 'Ares Vallis, Mars (19.33° N, 33.55° W)', 1, 'Martian Relic', 'First wheeled rover on another planet, measuring only 65 cm long and weighing 10.5 kg.', 'Confirmed basaltic volcanic rocks resembling andesite on Mars.', 'Established the foundational mobility archetype for Spirit, Opportunity, and Curiosity.'),
(6, 6, 'Spirit Rover', 'MER-A Spirit Rover', 'Rover', 'Long-range exploration of Gusev Crater for signs of past water.', 'Rocker-bogie chassis, solar panels, robotic arm, hazcams, navcams.', 'Pancam, Mini-TES, Mössbauer Spectrometer, Microscopic Imager, Rock Abrasion Tool.', 'X-band direct to Earth and UHF relay through Mars orbiters.', '2004-01-04 to 2010-03-22', 'Decommissioned', 'Gusev Crater, Mars (14.5684° S, 175.47263° E)', 1, 'Martian Relic', 'Drove 7.7 km across rugged Martian volcanic plains and the Columbia Hills.', 'Discovered pure silica deposits created by ancient hot springs or steam vents.', 'Turned a 90-day nominal mission into an epic 6-year geological odyssey.'),
(7, 7, 'Opportunity Rover', 'MER-B Opportunity Rover', 'Rover', 'Exploration of Meridiani Planum and endurance record holder on Mars.', 'Rocker-bogie mobility, solar arrays, robotic arm, rock abrasion tool.', 'Pancam, Microscopic Imager, Mössbauer Spectrometer, APXS.', 'X-band dish and UHF antenna to Mars Odyssey/MRO.', '2004-01-25 to 2018-06-10', 'Decommissioned', 'Perseverance Valley, Endeavour Crater, Mars (2.28° S, 354.74° E)', 1, 'Martian Relic', 'Operated for 5,111 sols (over 14 years), traveling 45.16 kilometers—the off-world driving record.', 'Discovered hematite spherules (blueberries) proving ancient standing liquid water.', 'Humanity''s greatest Martian marathon rover, resting in Perseverance Valley.'),
(8, 8, 'Curiosity Rover', 'MSL Curiosity Rover', 'Rover', 'Determine past habitability of Gale Crater and Mount Sharp.', 'Multi-Mission Radioisotope Thermoelectric Generator (MMRTG), 6-wheel rocker-bogie.', 'Mastcam, ChemCam laser spectrometer, SAM chemistry suite, CheMin X-ray diffraction.', 'X-band high-gain antenna and UHF link to Mars orbiters.', '2012-08-06 to Present', 'Operational', 'Gale Crater, Mount Sharp, Mars', 0, NULL, 'Car-sized robotic science rover actively traversing the strata of Mount Sharp.', 'Discovered ancient organic compounds, sulfur, and persistent lake sediments.', 'Demonstrated sky-crane planetary landing and ongoing decadal surface analysis.'),
(9, 9, 'Perseverance Rover', 'Mars 2020 Perseverance', 'Rover', 'Search for ancient biosignatures and collect sealed rock core samples.', 'MMRTG nuclear power, upgraded aluminum wheels, autonomous navigation (AutoNav).', 'SuperCam, PIXL, SHERLOC Raman spectrometer, RIMFAX radar, MOXIE.', 'UHF antenna relaying through MRO, MAVEN, and TGO orbiters.', '2021-02-18 to Present', 'Operational', 'Jezero Crater Delta, Mars', 0, NULL, 'State-of-the-art rover collecting geological cores for the future Mars Sample Return mission.', 'Detected diverse organic molecules and generated breathable oxygen from CO2 using MOXIE.', 'Leading the search for ancient Martian microbial life in a historic river delta.'),
(10, 10, 'Ingenuity Helicopter', 'Ingenuity Mars Helicopter', 'Drone', 'First powered aircraft flight in another planet''s atmosphere.', 'Carbon-fiber coaxial counter-rotating blades (2,400 RPM), solar panel, lithium-ion cells.', 'High-res terrain camera, solar tracker, inertial measurement unit.', 'Zigbee radio communication link to Perseverance rover.', '2021-02-18 to 2024-01-25', 'Decommissioned', 'Valinor Hills, Jezero Crater, Mars', 1, 'Martian Relic', 'The Wright Brothers moment of another world; completed 72 flights totaling over 128 minutes.', 'Aerial scout mapping safe navigation corridors for the Perseverance rover.', 'Opened the era of planetary aerial flight exploration.'),
(11, 11, 'Phoenix Lander', 'Mars Scout Phoenix', 'Lander', 'Excavate and analyze water ice in the Martian arctic permafrost.', 'Solar arrays, robotic articulated trenching arm, meteorological mast.', 'TEGA thermal analyzer, MECA microscopy/chemistry lab, SSI camera.', 'UHF link through Mars Odyssey orbiter.', '2008-05-25 to 2008-11-02', 'Decommissioned', 'Green Valley, Vastitas Borealis, Mars (68.2188° N, 234.2508° E)', 1, 'Martian Relic', 'First spacecraft to land in the Martian arctic permafrost zone.', 'Exposed subsurface white ice trenches that vaporized in sunlight, and identified perchlorate.', 'Proved the presence of near-surface water ice in the Martian high latitudes.'),
(12, 12, 'InSight Lander', 'InSight Mars Geophysical Lander', 'Lander', 'Geophysical probe studying the interior crust, mantle, and core of Mars.', 'UltraFlex solar arrays, robotic deployment arm.', 'SEIS seismometer, HP3 heat flow probe, RISE radio experiment.', 'X-band horn antenna and UHF link through MRO and 2U MarCO CubeSats.', '2018-11-26 to 2022-12-15', 'Decommissioned', 'Elysium Planitia, Mars (4.5024° N, 135.6234° E)', 1, 'Martian Relic', 'Stationary geophysical station that listened to the seismic heartbeat of Mars for 4 years.', 'Detected magnitude-5 monster marsquakes and measured the size of Mars''s molten iron core.', 'Created humanity''s first complete internal geological map of the Red Planet.'),
(13, 13, 'Chandrayaan-1 Orbiter', 'Chandrayaan-1 Spacecraft', 'Orbiter', 'Multi-spectral remote sensing and chemical mapping of the Moon.', 'Single solar panel generating 750W, bipropellant propulsion.', 'TMC terrain camera, HySI hyper-spectral imager, NASA Moon Mineralogy Mapper (M3).', 'X-band payload downlink and S-band telemetry to Indian Deep Space Network.', '2008-10-22 to 2009-08-29', 'Decommissioned', 'Lunar Orbit (100 km circular altitude)', 0, NULL, 'India''s historic first deep space mission, revolutionizing lunar science.', 'Unambiguously discovered water molecules bound in the lunar regolith and polar ice deposits.', 'Catalyzed the global modern race for lunar south pole exploration.'),
(14, 14, 'Vikram Lander', 'Chandrayaan-3 Vikram Lander', 'Lander', 'Safe soft-landing at high lunar latitude and in-situ science experiments.', 'Four 800N throttleable liquid engines, laser altimeters, hazard detection cameras.', 'ChASTE thermal probe, ILSA seismometer, RAMBHA Langmuir probe, LRA retroreflector.', 'Direct to Earth Deep Space Network and relay through Chandrayaan-2 orbiter.', '2023-08-23 to 2023-09-04', 'Decommissioned', 'Shiv Shakti Point, Moon (69.373° S, 32.319° E)', 1, 'Lunar Relic', 'Historic lunar lander that touched down at Shiv Shakti Point near 69° South latitude.', 'First soft landing near the Moon''s south polar region; measured high lunar surface thermal gradients.', 'Stands permanently at Shiv Shakti Point as a testament to Indian aerospace capability.'),
(15, 15, 'Pragyan Rover', 'Chandrayaan-3 Pragyan Rover', 'Rover', 'Roving surface chemical and elemental composition analysis.', '6-wheel rocker-bogie mechanism, solar panel, differential drive.', 'Laser Induced Breakdown Spectroscope (LIBS), Alpha Particle X-ray Spectrometer (APXS).', 'Direct wireless link to Vikram Lander.', '2023-08-23 to 2023-09-04', 'Decommissioned', 'Shiv Shakti Point, Moon (69.373° S, 32.319° E)', 1, 'Lunar Relic', '26-kg rover rolled down Vikram''s ramp and traveled over 100 meters across the lunar south pole.', 'Confirmed presence of Sulfur (S), Aluminum, Calcium, Iron, and Titanium in south polar soil.', 'Resting safely beside Vikram Lander after successfully completing its planned lunar day mission.'),
(16, 16, 'Hayabusa2 Spacecraft', 'Hayabusa2 Sample Return Probe', 'Flyby Probe', 'Asteroid exploration and return of pristine organic samples.', 'Four microwave discharge ion engines, solar arrays, chemical reaction wheels.', 'Optical Navigation Cameras, TIR thermal camera, NIRS3 spectrometer, Small Impactor (SCI).', 'X-band and Ka-band high-gain antennas communicating with Usuda and DSN.', '2014-12-03 to Present', 'Operational', 'Interplanetary Cruise (En route to 1998 KY26)', 0, NULL, 'Pioneering Japanese sample-return explorer that blasted an artificial crater on asteroid Ryugu.', 'Returned 5.4 grams of pristine asteroid material containing over 20 types of amino acids.', 'Demonstrated precision asteroid touch-and-go sampling and multiple rover deployments.'),
(17, 17, 'Rosetta Spacecraft', 'Rosetta Comet Orbiter', 'Orbiter', 'Orbit comet 67P and accompany it around perihelion.', 'Two massive 14-meter solar wings, bipropellant thrusters.', 'OSIRIS imaging system, ALICE UV spectrometer, VIRTIS thermal mapper, ROSINA mass spectrometer.', 'High-gain dish antenna communicating with ESA ESTRACK network.', '2004-03-02 to 2016-09-30', 'Destroyed', 'Deikoun Crater, Comet 67P/Churyumov–Gerasimenko', 1, 'Deep Space Relic', 'First spacecraft to orbit a comet nucleus and witness its sublimation as it neared the Sun.', 'Discovered glycine (an amino acid) and phosphorus in comet gas emissions.', 'Concluded its 12-year mission with a controlled descent directly onto the comet surface.'),
(18, 18, 'Philae Lander', 'Philae Comet Surface Lander', 'Lander', 'First in-situ physical and chemical examination of a comet nucleus surface.', 'Three-legged landing gear with ice screws and harpoons, flywheel stabilizer.', 'ÇIVA camera, ROLIS descent camera, COSAC organic chemistry suite, APXS, MUPUS thermal probe.', 'S-band relay link through Rosetta mothership.', '2014-11-12 to 2015-07-09', 'Abandoned', 'Abydos Site, Comet 67P/Churyumov–Gerasimenko', 1, 'Deep Space Relic', 'First human-made robot to softly land on the nucleus of a comet.', 'Bounced across cliffs before settling in shaded Abydos crevice; sniffed 16 organic carbon compounds.', 'Riding Comet 67P indefinitely through the solar system as an off-world relic.'),
(19, 19, 'New Horizons Spacecraft', 'New Horizons Pluto Explorer', 'Flyby Probe', 'Explore the Kuiper Belt, dwarf planets, and solar system frontier.', 'Single radioisotope thermoelectric generator (RTG), hydrazine propulsion.', 'Ralph optical/infrared imager, LORRI high-res telephoto camera, Alice UV spectrometer, SWAP.', '2.1-meter high-gain parabolic antenna transmitting across 50+ AU.', '2006-01-19 to Present', 'Operational', 'Kuiper Belt / Outer Space (58 AU from Earth)', 1, 'Deep Space Relic', 'Flew past Pluto at 49,600 km/h in July 2015, then visited contact binary Arrokoth in 2019.', 'Captured the iconic heart-shaped nitrogen glacier (Sputnik Planitia) on Pluto.', 'Currently exploring the distant outer heliosphere boundary alongside Voyagers.'),
(20, 20, 'Cassini Orbiter', 'Cassini-Huygens Saturn Orbiter', 'Orbiter', 'Comprehensive scientific study of Saturnian rings, moons, and magnetosphere.', '3x Radioisotope Thermoelectric Generators (RTGs), reaction wheels.', 'Imaging Science Subsystem (ISS), Cassini Radar, VIMS spectrometer, Cosmic Dust Analyzer.', '4-meter high-gain antenna communicating with NASA Deep Space Network.', '1997-10-15 to 2017-09-15', 'Destroyed', 'Saturn Upper Atmosphere (Controlled Plunge)', 0, NULL, 'Flagship spacecraft that orbited Saturn for 13 years and completed 294 orbits.', 'Discovered liquid hydrocarbon seas on Titan and geysers of salty water erupting from Enceladus.', 'Dived through Saturn''s rings during its Grand Finale before disintegrating into the atmosphere.'),
(21, 21, 'Hubble Space Telescope', 'Hubble Space Telescope (HST)', 'Space Telescope', 'Conduct high-resolution astronomical observations from above Earth''s atmosphere.', 'Dual solar arrays, fine guidance sensors, gyroscopes, reaction wheels.', 'Wide Field Camera 3 (WFC3), Cosmic Origins Spectrograph (COS), ACS, STIS.', 'High-gain steerable microwave antennas communicating via TDRSS satellites.', '1990-04-24 to Present', 'Operational', 'Low Earth Orbit (535 km, 28.5° inclination)', 0, NULL, 'The most celebrated telescope in human history, operating continuously for over three decades.', 'Determined the age of the universe (13.8B years) and discovered the acceleration of cosmic expansion.', 'Revolutionized all fields of modern astronomy and space science.'),
(22, 22, 'James Webb Space Telescope', 'James Webb Space Telescope (JWST)', 'Space Telescope', 'Observe the first light from early galaxies and characterize habitable exoplanet atmospheres.', 'Foldable 6.5-meter gold-plated beryllium mirror, 5-layer tennis-court-sized sunshield, cryocooler.', 'NIRCam, NIRSpec, MIRI (Mid-Infrared Instrument), NIRISS.', 'Ka-band high-rate transmitter communicating with Deep Space Network.', '2021-12-25 to Present', 'Operational', 'Sun-Earth Lagrange Point L2 (1.5 Million km from Earth)', 0, NULL, 'The premier astrophysics observatory in space, seeing back to 300 million years after the Big Bang.', 'Discovered the earliest known galaxies and detected carbon dioxide and methane in exoplanet atmospheres.', 'A crowning achievement of international collaboration between NASA, ESA, and CSA.'),
(23, 23, 'Sputnik 1 Satellite', 'Prosteyshiy Sputnik-1', 'Satellite', 'Test radio transmitter and measure orbital drag in upper atmosphere.', '58-cm polished aluminum-alloy sphere with four whip antennas, zinc-silver chemical batteries.', 'One-watt dual radio transmitter broadcasting at 20.005 MHz and 40.002 MHz.', 'Continuous radio beep telemetry heard by amateur radio operators worldwide.', '1957-10-04 to 1958-01-04', 'Destroyed', 'Burned up during atmospheric re-entry', 0, NULL, 'The world''s first artificial satellite, sparking the global Space Race and human space exploration.', 'Provided density data of the upper thermosphere from orbital drag measurements.', 'The historic spark that began humanity''s journey into the cosmos.'),
(24, 24, 'Aditya-L1 Spacecraft', 'Aditya-L1 Solar Explorer', 'Spacecraft', 'Continuous observation of the Sun''s corona, flares, and space weather.', 'Solar panels generating 1,000W, bipropellant liquid apogee motor.', 'VELC coronagraph, SUIT ultraviolet imager, ASPEX solar wind analyzer, PAPA plasma analyzer.', 'X-band downlink to ISRO Telemetry, Tracking and Command Network (ISTRAC).', '2023-09-02 to Present', 'Operational', 'Sun-Earth Lagrange Point L1 (Halo Orbit)', 0, NULL, 'India''s first dedicated space observatory studying solar coronal dynamics and space weather.', 'Monitors coronal mass ejections and solar storms before they impact Earth''s magnetosphere.', 'Provides real-time space weather alerting for satellite protection.'),
(25, 25, 'AstroSat Satellite', 'AstroSat Multi-wavelength Observatory', 'Space Telescope', 'Multi-wavelength simultaneous observation of cosmic sources.', 'Solar arrays generating 2,100W, reaction wheels, star sensors.', 'UVIT ultraviolet imaging telescope, LAXPC X-ray counter, CZTI hard X-ray imager, SXT.', 'X-band downlink to ISRO Bangalore ground station.', '2015-09-28 to Present', 'Operational', 'Low Earth Orbit (650 km, 6° inclination)', 0, NULL, 'First dedicated Indian multi-wavelength astronomy mission.', 'Discovered extreme UV light from distant galaxy AUDFs01 and observed coronal emission from young stars.', 'Operating successfully for over 9 years, far beyond its 5-year design life.'),
(26, 26, 'Gaia Spacecraft', 'Gaia Astrometry Spacecraft', 'Space Telescope', 'Ultra-high precision 3D astrometric mapping of the Milky Way.', 'Circular deployable sunshield with solar cells, micro-propulsion cold-gas thrusters.', 'Two optical telescopes sharing common focal plane of 106 CCD sensors (almost 1 Gigapixel).', 'High-bandwidth phased array antenna communicating with ESA tracking stations.', '2013-12-19 to Present', 'Operational', 'Sun-Earth Lagrange Point L2 (Lissajous Orbit)', 0, NULL, 'Constructing the largest and most accurate 3D map of our galaxy and stellar motions.', 'Cataloged positions, motions, and colors for nearly 2 billion stars in the Milky Way.', 'Revealed the history of ancient galactic collisions that formed our home galaxy.'),
(27, 27, 'Zhurong Rover', 'Tianwen-1 Zhurong Rover', 'Rover', 'Explore the surface topography, magnetic fields, and water ice in Utopia Planitia.', '4 butterfly-wing solar panels, active suspension rocker system, sub-surface radar.', 'Navcam, Multispectral Camera, Mars Surface Magnetic Field Detector, RoPeR ground-penetrating radar.', 'UHF link through Tianwen-1 orbiter and direct X-band link.', '2021-05-15 to 2022-05-20', 'Decommissioned', 'Utopia Planitia, Mars (25.1° N, 109.9° E)', 1, 'Martian Relic', 'First Chinese Mars rover, drove 1,921 meters across the vast northern lowlands.', 'Detected layered subsurface structures indicative of ancient sedimentary floods.', 'Marks China''s arrival as a major rover operator on Mars, resting in Utopia Planitia.'),
(28, 28, 'SLIM Lander', 'Smart Lander for Investigating Moon', 'Lander', 'Demonstrate 100-meter pinpoint landing technology on steep crater slopes.', 'Ceramic thruster engines, vision-based crater navigation, aluminum crushable landing legs.', 'Multi-band camera, laser rangefinder, deployment systems for LEV-1 and LEV-2.', 'S-band communication link to JAXA Usuda Deep Space Center.', '2024-01-19 to 2024-04-29', 'Decommissioned', 'Shioli Crater, Moon (13.3160° S, 25.2510° E)', 1, 'Lunar Relic', 'Achieved unprecedented pinpoint landing accuracy, touching down just 55 meters from its target.', 'Survived three brutal -130°C lunar nights and transmitted high-res spectroscopy of lunar olivine.', 'Established Japan as the 5th nation to soft-land on the Moon, resting at Shioli Crater.'),
(29, 29, 'Surveyor 3 Lander', 'Surveyor 3 Lunar Lander', 'Lander', 'Perform soft landing and dig lunar surface with motorized scoop.', 'Throttleable vernier engines, radar altimeter, tripod landing gear with strain gauges.', 'Television camera, surface soil mechanics sampler scoop.', 'Planar array high-gain antenna communicating with NASA DSN.', '1967-04-20 to 1967-05-04', 'Abandoned', 'Oceanus Procellarum, Moon (3.0163° S, 23.4180° W)', 1, 'Lunar Relic', 'Landed in a crater; later visited by Apollo 12 astronauts Pete Conrad and Alan Bean.', 'Scooped trenches up to 17.5 cm deep proving soil consistency and bearing strength.', 'The camera brought back to Earth by Apollo 12 provided valuable data on long-term lunar exposure.'),
(30, 30, 'International Space Station', 'ISS Modular Orbital Complex', 'Space Station', 'Inhabited orbital laboratory for scientific research, biology, and technology.', 'Giant solar arrays spanning 73 meters generating 120 kW, Truss structure, Canadarm2.', 'Columbus laboratory, Destiny laboratory, Kibo module, Cupola observation dome, AMS-02.', 'Ku-band high rate data system and S-band communications via TDRS constellation.', '1998-11-20 to Present', 'Operational', 'Low Earth Orbit (418 km altitude, 51.6° inclination)', 0, NULL, 'The crowning jewel of human peaceful international cooperation in space.', 'Hosted over 270 astronauts from 21 nations and conducted over 3,000 microgravity scientific experiments.', 'The longest continuous human presence in space, orbiting Earth every 92 minutes.');

-- 6. IMAGES
INSERT INTO `images` (`id`, `equipment_id`, `mission_id`, `image_url`, `page_url`, `title`, `description`, `credit`, `license`, `source`, `image_type`) VALUES
(1, 2, 2, 'https://images-assets.nasa.gov/image/as15-88-11866/as15-88-11866~orig.jpg', 'https://images.nasa.gov/details/as15-88-11866', 'Apollo 15 Lunar Roving Vehicle on Lunar Surface', 'Astronaut Dave Scott with the Apollo 15 Lunar Roving Vehicle parked near Hadley Rille with Apennine mountain range in background.', 'NASA / Dave Scott / Jim Irwin', 'Public Domain', 'NASA Image and Video Library', 'hero'),
(2, 2, 2, 'https://images-assets.nasa.gov/image/as15-85-11471/as15-85-11471~orig.jpg', 'https://images.nasa.gov/details/as15-85-11471', 'Apollo 15 LRV Traversal', 'Apollo 15 Rover tracks extending across the lunar regolith towards Mount Hadley.', 'NASA', 'Public Domain', 'NASA Image and Video Library', 'surface'),
(3, 7, 7, 'https://images-assets.nasa.gov/image/PIA18076/PIA18076~orig.jpg', 'https://images.nasa.gov/details/PIA18076', 'Opportunity Rover Self-Portrait on Mars', 'Mosaic self-portrait of Opportunity Rover taken by its panoramic camera atop Murray Ridge.', 'NASA/JPL-Caltech/Cornell Univ./Arizona State Univ.', 'Public Domain', 'NASA/JPL Photojournal', 'hero'),
(4, 7, 7, 'https://images-assets.nasa.gov/image/PIA05540/PIA05540~orig.jpg', 'https://images.nasa.gov/details/PIA05540', 'Martian Blueberries in Endurance Crater', 'Hematite-rich spherical concretions photographed up close by Opportunity''s microscopic imager.', 'NASA/JPL-Caltech/Cornell/USGS', 'Public Domain', 'NASA/JPL Photojournal', 'surface'),
(5, 3, 3, 'https://images-assets.nasa.gov/image/PIA22566/PIA22566~orig.jpg', 'https://images.nasa.gov/details/PIA22566', 'Voyager 1 in Deep Space', 'Artist concept of Voyager 1 traveling through the interstellar medium beyond the heliosphere.', 'NASA/JPL-Caltech', 'Public Domain', 'NASA/JPL Photojournal', 'hero'),
(6, 1, 1, 'https://images-assets.nasa.gov/image/as11-40-5927/as11-40-5927~orig.jpg', 'https://images.nasa.gov/details/as11-40-5927', 'Apollo 11 Lunar Module Eagle', 'The Apollo 11 Lunar Module Eagle on the Moon, with Buzz Aldrin descending the ladder.', 'NASA / Neil Armstrong', 'Public Domain', 'NASA Image and Video Library', 'hero'),
(7, 8, 8, 'https://images-assets.nasa.gov/image/PIA19920/PIA19920~orig.jpg', 'https://images.nasa.gov/details/PIA19920', 'Curiosity Rover at Namib Dune', 'Self-portrait of Curiosity rover examining dark sand dunes at the base of Mount Sharp in Gale Crater.', 'NASA/JPL-Caltech/MSSS', 'Public Domain', 'NASA/JPL Photojournal', 'hero'),
(8, 10, 10, 'https://images-assets.nasa.gov/image/PIA24657/PIA24657~orig.jpg', 'https://images.nasa.gov/details/PIA24657', 'Ingenuity Helicopter in Flight on Mars', 'Ingenuity Mars Helicopter hovering in the thin Martian atmosphere over Jezero Crater during historic Flight 3.', 'NASA/JPL-Caltech', 'Public Domain', 'NASA/JPL Photojournal', 'operation'),
(9, 14, 14, 'https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?w=800&auto=format&fit=crop', 'https://www.isro.gov.in', 'Vikram Lander on Lunar South Pole', 'Vikram Lander photographed on the lunar regolith after soft landing at Shiv Shakti Point.', 'ISRO', 'Fair Use / Educational', 'ISRO Chandrayaan-3 Gallery', 'hero'),
(10, 21, 21, 'https://images-assets.nasa.gov/image/hubble-stellar-birth-in-carina-nebula/hubble-stellar-birth-in-carina-nebula~orig.jpg', 'https://images.nasa.gov', 'Hubble View of Carina Nebula', 'Stunning mystic mountain pillars of gas and dust inside the Carina Nebula captured by Hubble.', 'NASA, ESA, and M. Livio and the Hubble 20th Anniversary Team (STScI)', 'Public Domain', 'HubbleSite', 'hero');

-- 7. TIMELINE EVENTS
INSERT INTO `timeline_events` (`id`, `year`, `title`, `mission_id`, `equipment_id`, `description`, `image_url`, `importance`) VALUES
(1, 1957, 'Sputnik 1 — Dawn of the Space Age', 22, 23, 'The Soviet Union launches Sputnik 1 into low Earth orbit, inaugurating the Space Age and proving orbital flight.', 'https://images.unsplash.com/photo-1517976487502-d7da6e3820a1?w=600&auto=format&fit=crop', 'Crucial'),
(2, 1969, 'Apollo 11 — First Human Footsteps on the Moon', 1, 1, 'Neil Armstrong and Buzz Aldrin land Lunar Module Eagle on the Sea of Tranquility, taking humanity''s giant leap.', 'https://images-assets.nasa.gov/image/as11-40-5927/as11-40-5927~orig.jpg', 'Crucial'),
(3, 1971, 'Apollo 15 — Wheels on the Lunar Surface', 2, 2, 'Astronauts Dave Scott and Jim Irwin drive the first Lunar Roving Vehicle 28 kilometers across the Apennine mountains.', 'https://images-assets.nasa.gov/image/as15-88-11866/as15-88-11866~orig.jpg', 'High'),
(4, 1977, 'Voyager 1 & 2 — The Grand Tour & Interstellar Message', 3, 3, 'NASA launches the twin Voyager spacecraft carrying the Golden Record on a trajectory toward the stars.', 'https://images-assets.nasa.gov/image/PIA22566/PIA22566~orig.jpg', 'Crucial'),
(5, 1990, 'Hubble Space Telescope Deployed', 20, 21, 'Space Shuttle Discovery deploys the Hubble Space Telescope, opening humanity''s eyes to the deep universe.', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop', 'High'),
(6, 1997, 'Mars Pathfinder & Cassini-Huygens Launch', 5, 5, 'Sojourner rover touches down on Mars while the flagship Cassini-Huygens mission departs for Saturn.', 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=600&auto=format&fit=crop', 'High'),
(7, 2004, 'Spirit & Opportunity Land on Mars', 7, 7, 'Twin Martian exploration rovers land on opposite sides of Mars, beginning 14 years of water discovery.', 'https://images-assets.nasa.gov/image/PIA18076/PIA18076~orig.jpg', 'High'),
(8, 2012, 'Curiosity Lands & Voyager 1 Enters Interstellar Space', 8, 8, 'Curiosity executes the sky-crane landing inside Gale Crater while Voyager 1 crosses the heliopause into the stars.', 'https://images-assets.nasa.gov/image/PIA19920/PIA19920~orig.jpg', 'Crucial'),
(9, 2021, 'Perseverance, Ingenuity & James Webb Telescope', 21, 22, 'Perseverance lands on Mars with Ingenuity helicopter, and the revolutionary James Webb Space Telescope launches on Christmas Day.', 'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=600&auto=format&fit=crop', 'Crucial'),
(10, 2023, 'Chandrayaan-3 South Pole Landing', 14, 14, 'ISRO''s Chandrayaan-3 makes history as the first spacecraft to soft land near the lunar south pole at Shiv Shakti Point.', 'https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?w=600&auto=format&fit=crop', 'Crucial');

-- 8. SOURCES
INSERT INTO `sources` (`id`, `mission_id`, `equipment_id`, `source_name`, `source_url`, `source_type`, `description`, `verified_date`) VALUES
(1, 1, 1, 'NASA Apollo 11 Mission Overview', 'https://www.nasa.gov/mission_pages/apollo/apollo-11.html', 'official', 'Official NASA mission report and landing telemetry records.', '2026-01-15'),
(2, 2, 2, 'Apollo 15 Lunar Surface Journal', 'https://www.nasa.gov/history/alsj/a15/a15.html', 'official', 'Complete transcripts, photos, and engineering logs of the Apollo 15 LRV operations.', '2026-01-15'),
(3, 3, 3, 'NASA JPL Voyager Interstellar Mission', 'https://voyager.jpl.nasa.gov/', 'official', 'Real-time telemetry, distance monitors, and scientific logs for Voyager 1 and 2.', '2026-02-10'),
(4, 7, 7, 'NASA JPL Mars Exploration Rovers Archive', 'https://mars.nasa.gov/mer/', 'official', 'Comprehensive mission science data, traverse maps, and telemetry for Opportunity and Spirit.', '2026-02-10'),
(5, 14, 14, 'ISRO Chandrayaan-3 Official Portal', 'https://www.isro.gov.in/Chandrayaan3.html', 'official', 'Scientific payload reports, coordinates of Shiv Shakti Point, and in-situ results.', '2026-03-01'),
(6, 21, 22, 'NASA / ESA James Webb Space Telescope Center', 'https://webb.nasa.gov/', 'official', 'Full science documentation, spectroscopic releases, and deployment history.', '2026-03-01');
